apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-api
  description: Search API for the wayback machine
  owner: Backstage
spec:
  type: openapi
  lifecycle: production
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/search/1.0.0/openapi.yaml
